### PR TITLE
add docker development support

### PR DESCRIPTION
**Pull request by kevingentile**
* add setuptools support
* add Dockerfile
* add docker-compose file
* add environment override
* add migrations

### CODE REVIEW

**Comment by LogicalSoIutions** [comment]
I appreciate your efforts on this one, but, I don't really see any usefulness for Docker on this project. The bot isn't really able to ran by anybody else unless they are going to be making their own database of data and also setup their own flea-market checking system or API.

**Comment by kevingentile** [comment]
@LogicalSoIutions Sure, do you mind adding an open source license to the project?

To add, this is more Docker as a development platform than anything. You need Migrations to run any database setup/changes and you need to be able to override configuration settings without pushing a static config file to VCS.

`docker-compose up` initializes a portable development database and migrations run as part of startup if the tables don't exist. You can optionally run the bot as a container or just expose the mysql container to your localhost and execute python locally.

`setup.py` specifies your dependencies. You can manually install modules locally but right now the bot knows nothing other than these modules should exist somewhere. With it: `pip install .` and you have everything, no guess work.

For flea marketing, the "future" plan was BSG would open some level of API access (or third parties) so that data doesn't necessarily need to live in a local database, but maybe cached.

I may have been mistaken in assuming that this project was looking for outside contributors, but these changes minimize the hurdles to start development.

**Comment by LogicalSoIutions** [comment]
I am definitely down for outside contributors - maybe we can chat on Discord?

I am storing nothing in a database except for the list of Twitch Users, Cool-downs, and Language. 

All of the functions currently use an API call - I would just change my source for the API if BSG were to ever release this type of info publicly.

**Comment by kevingentile** [comment]
@LogicalSoIutions i'll shoot you a message on discord

**Comment by kevingentile** [comment]
https://docs.docker.com/get-started/

https://hub.docker.com/_/python 

https://hub.docker.com/_/mariadb

**Pull request closed without merging**
